name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: windows-2025-vs2026
    steps:
      # actions/checkout v7.0.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          lfs: true
          persist-credentials: false
      # actions/setup-python v6.2.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"

      - name: Install Pixi
        shell: pwsh
        run: |
          iwr -UseBasicParsing https://pixi.sh/install.ps1 | iex
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.pixi\bin"

      - name: Install dependencies
        run: pixi install
      - name: Run tests
        run: pixi run test
